import Head from 'next/head'
import { BsFile, BsFiles, BsFileX } from 'react-icons/bs';
import StickerButton from '../components/StickerButton';
import StickerGroup from '../components/StickerGroup';

export default function Home() {
  const stickers = [
    { id: 0, name: 'FIF 1', group: 'FIFA', qty: 0 },
    { id: 1, name: 'FIF 2', group: 'FIFA', qty: 0 },
    { id: 2, name: 'FIF 3', group: 'FIFA', qty: 0 },
    { id: 3, name: 'FIF 4', group: 'FIFA', qty: 0 },
    { id: 4, name: 'FIF 5', group: 'FIFA', qty: 0 },
    { id: 5, name: 'FIF 6', group: 'FIFA', qty: 0 },
    { id: 6, name: 'FIF 7', group: 'FIFA', qty: 0 },
    { id: 7, name: 'STA 1', group: 'Stadiums', qty: 0 },
    { id: 8, name: 'STA 2', group: 'Stadiums', qty: 0 },
    { id: 9, name: 'STA 3', group: 'Stadiums', qty: 0 },
    { id: 10, name: 'STA 4', group: 'Stadiums', qty: 0 },
    { id: 11, name: 'STA 5', group: 'Stadiums', qty: 0 },
    { id: 12, name: 'STA 6', group: 'Stadiums', qty: 0 },
    { id: 13, name: 'STA 7', group: 'Stadiums', qty: 0 },
    { id: 14, name: 'STA 8', group: 'Stadiums', qty: 0 },
    { id: 15, name: 'POS 1', group: 'Cartazes', qty: 0 },
    { id: 16, name: 'POS 2', group: 'Cartazes', qty: 0 },
    { id: 17, name: 'POS 3', group: 'Cartazes', qty: 0 },
    { id: 18, name: 'POS 4', group: 'Cartazes', qty: 0 },
    { id: 19, name: 'POS 5', group: 'Cartazes', qty: 0 },

    { id: 20, name: 'QAT 1', group: 'Qatar', qty: 0 },
    { id: 21, name: 'QAT 2', group: 'Qatar', qty: 0 },
    { id: 22, name: 'QAT 3', group: 'Qatar', qty: 0 },
    { id: 23, name: 'QAT 4', group: 'Qatar', qty: 0 },
    { id: 24, name: 'QAT 5', group: 'Qatar', qty: 0 },
    { id: 25, name: 'QAT 6', group: 'Qatar', qty: 0 },
    { id: 26, name: 'QAT 7', group: 'Qatar', qty: 0 },
    { id: 27, name: 'QAT 8', group: 'Qatar', qty: 0 },
    { id: 28, name: 'QAT 9', group: 'Qatar', qty: 0 },
    { id: 29, name: 'QAT 10', group: 'Qatar', qty: 0 },
    { id: 30, name: 'QAT 11', group: 'Qatar', qty: 0 },
    { id: 31, name: 'QAT 12', group: 'Qatar', qty: 0 },
    { id: 32, name: 'QAT 13', group: 'Qatar', qty: 0 },
    { id: 33, name: 'QAT 14', group: 'Qatar', qty: 0 },
    { id: 34, name: 'QAT 15', group: 'Qatar', qty: 0 },
    { id: 35, name: 'QAT 16', group: 'Qatar', qty: 0 },
    { id: 36, name: 'QAT 17', group: 'Qatar', qty: 0 },
    { id: 37, name: 'QAT 18', group: 'Qatar', qty: 0 },
    { id: 38, name: 'QAT 19', group: 'Qatar', qty: 0 },

    { id: 39, name: 'ECU 1', group: 'Ecuador', qty: 0 },
    { id: 40, name: 'ECU 2', group: 'Ecuador', qty: 0 },
    { id: 41, name: 'ECU 3', group: 'Ecuador', qty: 0 },
    { id: 42, name: 'ECU 4', group: 'Ecuador', qty: 0 },
    { id: 43, name: 'ECU 5', group: 'Ecuador', qty: 0 },
    { id: 44, name: 'ECU 6', group: 'Ecuador', qty: 0 },
    { id: 45, name: 'ECU 7', group: 'Ecuador', qty: 0 },
    { id: 46, name: 'ECU 8', group: 'Ecuador', qty: 0 },
    { id: 47, name: 'ECU 9', group: 'Ecuador', qty: 0 },
    { id: 48, name: 'ECU 10', group: 'Ecuador', qty: 0 },
    { id: 49, name: 'ECU 11', group: 'Ecuador', qty: 0 },
    { id: 50, name: 'ECU 12', group: 'Ecuador', qty: 0 },
    { id: 51, name: 'ECU 13', group: 'Ecuador', qty: 0 },
    { id: 52, name: 'ECU 14', group: 'Ecuador', qty: 0 },
    { id: 53, name: 'ECU 15', group: 'Ecuador', qty: 0 },
    { id: 54, name: 'ECU 16', group: 'Ecuador', qty: 0 },
    { id: 55, name: 'ECU 17', group: 'Ecuador', qty: 0 },
    { id: 56, name: 'ECU 18', group: 'Ecuador', qty: 0 },
    { id: 57, name: 'ECU 19', group: 'Ecuador', qty: 0 },

    { id: 58, name: 'SEN 1', group: 'Senegal', qty: 0 },
    { id: 59, name: 'SEN 2', group: 'Senegal', qty: 0 },
    { id: 60, name: 'SEN 3', group: 'Senegal', qty: 0 },
    { id: 61, name: 'SEN 4', group: 'Senegal', qty: 0 },
    { id: 62, name: 'SEN 5', group: 'Senegal', qty: 0 },
    { id: 63, name: 'SEN 6', group: 'Senegal', qty: 0 },
    { id: 64, name: 'SEN 7', group: 'Senegal', qty: 0 },
    { id: 65, name: 'SEN 8', group: 'Senegal', qty: 0 },
    { id: 66, name: 'SEN 9', group: 'Senegal', qty: 0 },
    { id: 67, name: 'SEN 10', group: 'Senegal', qty: 0 },
    { id: 68, name: 'SEN 11', group: 'Senegal', qty: 0 },
    { id: 69, name: 'SEN 12', group: 'Senegal', qty: 0 },
    { id: 70, name: 'SEN 13', group: 'Senegal', qty: 0 },
    { id: 71, name: 'SEN 14', group: 'Senegal', qty: 0 },
    { id: 72, name: 'SEN 15', group: 'Senegal', qty: 0 },
    { id: 73, name: 'SEN 16', group: 'Senegal', qty: 0 },
    { id: 74, name: 'SEN 17', group: 'Senegal', qty: 0 },
    { id: 75, name: 'SEN 18', group: 'Senegal', qty: 0 },
    { id: 76, name: 'SEN 19', group: 'Senegal', qty: 0 },

    { id: 77, name: 'NED 1', group: 'Holanda', qty: 0 },
    { id: 78, name: 'NED 2', group: 'Holanda', qty: 0 },
    { id: 79, name: 'NED 3', group: 'Holanda', qty: 0 },
    { id: 80, name: 'NED 4', group: 'Holanda', qty: 0 },
    { id: 81, name: 'NED 5', group: 'Holanda', qty: 0 },
    { id: 82, name: 'NED 6', group: 'Holanda', qty: 0 },
    { id: 83, name: 'NED 7', group: 'Holanda', qty: 0 },
    { id: 84, name: 'NED 8', group: 'Holanda', qty: 0 },
    { id: 85, name: 'NED 9', group: 'Holanda', qty: 0 },
    { id: 86, name: 'NED 10', group: 'Holanda', qty: 0 },
    { id: 87, name: 'NED 11', group: 'Holanda', qty: 0 },
    { id: 88, name: 'NED 12', group: 'Holanda', qty: 0 },
    { id: 89, name: 'NED 13', group: 'Holanda', qty: 0 },
    { id: 90, name: 'NED 14', group: 'Holanda', qty: 0 },
    { id: 91, name: 'NED 15', group: 'Holanda', qty: 0 },
    { id: 92, name: 'NED 16', group: 'Holanda', qty: 0 },
    { id: 93, name: 'NED 17', group: 'Holanda', qty: 0 },
    { id: 94, name: 'NED 18', group: 'Holanda', qty: 0 },
    { id: 95, name: 'NED 19', group: 'Holanda', qty: 0 },

    { id: 96, name: 'ENG 1', group: 'Inglaterra', qty: 0 },
    { id: 97, name: 'ENG 2', group: 'Inglaterra', qty: 0 },
    { id: 98, name: 'ENG 3', group: 'Inglaterra', qty: 0 },
    { id: 99, name: 'ENG 4', group: 'Inglaterra', qty: 0 },
    { id: 100, name: 'ENG 5', group: 'Inglaterra', qty: 0 },
    { id: 101, name: 'ENG 6', group: 'Inglaterra', qty: 0 },
    { id: 102, name: 'ENG 7', group: 'Inglaterra', qty: 0 },
    { id: 103, name: 'ENG 8', group: 'Inglaterra', qty: 0 },
    { id: 104, name: 'ENG 9', group: 'Inglaterra', qty: 0 },
    { id: 105, name: 'ENG 10', group: 'Inglaterra', qty: 0 },
    { id: 106, name: 'ENG 11', group: 'Inglaterra', qty: 0 },
    { id: 107, name: 'ENG 12', group: 'Inglaterra', qty: 0 },
    { id: 108, name: 'ENG 13', group: 'Inglaterra', qty: 0 },
    { id: 109, name: 'ENG 14', group: 'Inglaterra', qty: 0 },
    { id: 110, name: 'ENG 15', group: 'Inglaterra', qty: 0 },
    { id: 111, name: 'ENG 16', group: 'Inglaterra', qty: 0 },
    { id: 112, name: 'ENG 17', group: 'Inglaterra', qty: 0 },
    { id: 113, name: 'ENG 18', group: 'Inglaterra', qty: 0 },
    { id: 114, name: 'ENG 19', group: 'Inglaterra', qty: 0 },

    { id: 115, name: 'IRN 1', group: 'Irã', qty: 0 },
    { id: 116, name: 'IRN 2', group: 'Irã', qty: 0 },
    { id: 117, name: 'IRN 3', group: 'Irã', qty: 0 },
    { id: 118, name: 'IRN 4', group: 'Irã', qty: 0 },
    { id: 119, name: 'IRN 5', group: 'Irã', qty: 0 },
    { id: 120, name: 'IRN 6', group: 'Irã', qty: 0 },
    { id: 121, name: 'IRN 7', group: 'Irã', qty: 0 },
    { id: 122, name: 'IRN 8', group: 'Irã', qty: 0 },
    { id: 123, name: 'IRN 9', group: 'Irã', qty: 0 },
    { id: 124, name: 'IRN 10', group: 'Irã', qty: 0 },
    { id: 125, name: 'IRN 11', group: 'Irã', qty: 0 },
    { id: 126, name: 'IRN 12', group: 'Irã', qty: 0 },
    { id: 127, name: 'IRN 13', group: 'Irã', qty: 0 },
    { id: 128, name: 'IRN 14', group: 'Irã', qty: 0 },
    { id: 129, name: 'IRN 15', group: 'Irã', qty: 0 },
    { id: 130, name: 'IRN 16', group: 'Irã', qty: 0 },
    { id: 131, name: 'IRN 17', group: 'Irã', qty: 0 },
    { id: 132, name: 'IRN 18', group: 'Irã', qty: 0 },
    { id: 133, name: 'IRN 19', group: 'Irã', qty: 0 },

    { id: 115, name: 'USA 1', group: 'EUA', qty: 0 },
    { id: 116, name: 'USA 2', group: 'EUA', qty: 0 },
    { id: 117, name: 'USA 3', group: 'EUA', qty: 0 },
    { id: 118, name: 'USA 4', group: 'EUA', qty: 0 },
    { id: 119, name: 'USA 5', group: 'EUA', qty: 0 },
    { id: 120, name: 'USA 6', group: 'EUA', qty: 0 },
    { id: 121, name: 'USA 7', group: 'EUA', qty: 0 },
    { id: 122, name: 'USA 8', group: 'EUA', qty: 0 },
    { id: 123, name: 'USA 9', group: 'EUA', qty: 0 },
    { id: 124, name: 'USA 10', group: 'EUA', qty: 0 },
    { id: 125, name: 'USA 11', group: 'EUA', qty: 0 },
    { id: 126, name: 'USA 12', group: 'EUA', qty: 0 },
    { id: 127, name: 'USA 13', group: 'EUA', qty: 0 },
    { id: 128, name: 'USA 14', group: 'EUA', qty: 0 },
    { id: 129, name: 'USA 15', group: 'EUA', qty: 0 },
    { id: 130, name: 'USA 16', group: 'EUA', qty: 0 },
    { id: 131, name: 'USA 17', group: 'EUA', qty: 0 },
    { id: 132, name: 'USA 18', group: 'EUA', qty: 0 },
    { id: 133, name: 'USA 19', group: 'EUA', qty: 0 },

    { id: 115, name: 'WAL 1', group: 'Camarões', qty: 0 },
    { id: 116, name: 'WAL 2', group: 'Camarões', qty: 0 },
    { id: 117, name: 'WAL 3', group: 'Camarões', qty: 0 },
    { id: 118, name: 'WAL 4', group: 'Camarões', qty: 0 },
    { id: 119, name: 'WAL 5', group: 'Camarões', qty: 0 },
    { id: 120, name: 'WAL 6', group: 'Camarões', qty: 0 },
    { id: 121, name: 'WAL 7', group: 'Camarões', qty: 0 },
    { id: 122, name: 'WAL 8', group: 'Camarões', qty: 0 },
    { id: 123, name: 'WAL 9', group: 'Camarões', qty: 0 },
    { id: 124, name: 'WAL 10', group: 'Camarões', qty: 0 },
    { id: 125, name: 'WAL 11', group: 'Camarões', qty: 0 },
    { id: 126, name: 'WAL 12', group: 'Camarões', qty: 0 },
    { id: 127, name: 'WAL 13', group: 'Camarões', qty: 0 },
    { id: 128, name: 'WAL 14', group: 'Camarões', qty: 0 },
    { id: 129, name: 'WAL 15', group: 'Camarões', qty: 0 },
    { id: 130, name: 'WAL 16', group: 'Camarões', qty: 0 },
    { id: 131, name: 'WAL 17', group: 'Camarões', qty: 0 },
    { id: 132, name: 'WAL 18', group: 'Camarões', qty: 0 },
    { id: 133, name: 'WAL 19', group: 'Camarões', qty: 0 },

    { id: 115, name: 'ARG 1', group: 'Argentina', qty: 0 },
    { id: 116, name: 'ARG 2', group: 'Argentina', qty: 0 },
    { id: 117, name: 'ARG 3', group: 'Argentina', qty: 0 },
    { id: 118, name: 'ARG 4', group: 'Argentina', qty: 0 },
    { id: 119, name: 'ARG 5', group: 'Argentina', qty: 0 },
    { id: 120, name: 'ARG 6', group: 'Argentina', qty: 0 },
    { id: 121, name: 'ARG 7', group: 'Argentina', qty: 0 },
    { id: 122, name: 'ARG 8', group: 'Argentina', qty: 0 },
    { id: 123, name: 'ARG 9', group: 'Argentina', qty: 0 },
    { id: 124, name: 'ARG 10', group: 'Argentina', qty: 0 },
    { id: 125, name: 'ARG 11', group: 'Argentina', qty: 0 },
    { id: 126, name: 'ARG 12', group: 'Argentina', qty: 0 },
    { id: 127, name: 'ARG 13', group: 'Argentina', qty: 0 },
    { id: 128, name: 'ARG 14', group: 'Argentina', qty: 0 },
    { id: 129, name: 'ARG 15', group: 'Argentina', qty: 0 },
    { id: 130, name: 'ARG 16', group: 'Argentina', qty: 0 },
    { id: 131, name: 'ARG 17', group: 'Argentina', qty: 0 },
    { id: 132, name: 'ARG 18', group: 'Argentina', qty: 0 },
    { id: 133, name: 'ARG 19', group: 'Argentina', qty: 0 },

    { id: 115, name: 'KSA 1', group: 'Arábia Saudita', qty: 0 },
    { id: 116, name: 'KSA 2', group: 'Arábia Saudita', qty: 0 },
    { id: 117, name: 'KSA 3', group: 'Arábia Saudita', qty: 0 },
    { id: 118, name: 'KSA 4', group: 'Arábia Saudita', qty: 0 },
    { id: 119, name: 'KSA 5', group: 'Arábia Saudita', qty: 0 },
    { id: 120, name: 'KSA 6', group: 'Arábia Saudita', qty: 0 },
    { id: 121, name: 'KSA 7', group: 'Arábia Saudita', qty: 0 },
    { id: 122, name: 'KSA 8', group: 'Arábia Saudita', qty: 0 },
    { id: 123, name: 'KSA 9', group: 'Arábia Saudita', qty: 0 },
    { id: 124, name: 'KSA 10', group: 'Arábia Saudita', qty: 0 },
    { id: 125, name: 'KSA 11', group: 'Arábia Saudita', qty: 0 },
    { id: 126, name: 'KSA 12', group: 'Arábia Saudita', qty: 0 },
    { id: 127, name: 'KSA 13', group: 'Arábia Saudita', qty: 0 },
    { id: 128, name: 'KSA 14', group: 'Arábia Saudita', qty: 0 },
    { id: 129, name: 'KSA 15', group: 'Arábia Saudita', qty: 0 },
    { id: 130, name: 'KSA 16', group: 'Arábia Saudita', qty: 0 },
    { id: 131, name: 'KSA 17', group: 'Arábia Saudita', qty: 0 },
    { id: 132, name: 'KSA 18', group: 'Arábia Saudita', qty: 0 },
    { id: 133, name: 'KSA 19', group: 'Arábia Saudita', qty: 0 },

    { id: 115, name: 'MEX 1', group: 'México', qty: 0 },
    { id: 116, name: 'MEX 2', group: 'México', qty: 0 },
    { id: 117, name: 'MEX 3', group: 'México', qty: 0 },
    { id: 118, name: 'MEX 4', group: 'México', qty: 0 },
    { id: 119, name: 'MEX 5', group: 'México', qty: 0 },
    { id: 120, name: 'MEX 6', group: 'México', qty: 0 },
    { id: 121, name: 'MEX 7', group: 'México', qty: 0 },
    { id: 122, name: 'MEX 8', group: 'México', qty: 0 },
    { id: 123, name: 'MEX 9', group: 'México', qty: 0 },
    { id: 124, name: 'MEX 10', group: 'México', qty: 0 },
    { id: 125, name: 'MEX 11', group: 'México', qty: 0 },
    { id: 126, name: 'MEX 12', group: 'México', qty: 0 },
    { id: 127, name: 'MEX 13', group: 'México', qty: 0 },
    { id: 128, name: 'MEX 14', group: 'México', qty: 0 },
    { id: 129, name: 'MEX 15', group: 'México', qty: 0 },
    { id: 130, name: 'MEX 16', group: 'México', qty: 0 },
    { id: 131, name: 'MEX 17', group: 'México', qty: 0 },
    { id: 132, name: 'MEX 18', group: 'México', qty: 0 },
    { id: 133, name: 'MEX 19', group: 'México', qty: 0 },
  ];

  const groups = [...new Set(stickers.map(item => item.group))];

  console.log(groups)

  return (
    <>
      <header className='bg-white text-black w-full py-5 px-5 border-gray-200  border-0 border-b flex flex-column fixed top-0 z-10'>
        <div>
          <h1 className='text-gray-600 text-xl font-bold mb-2'>Copa do Qatar 2022</h1>
          <p className='text-gray-600 text-sm'>Totais: 0 | Repetidas: 0 | Faltantes: 0</p>
        </div>
      </header>

      <main className='bg-white text-black px-5 pt-32 pb-36 overflow-auto'>
        { groups.map((group, ix) => (
          <StickerGroup
            key={ ix }
            name={ group }
            stickers={ stickers.filter(sticker => sticker.group === group)}
          />
        ))}
      </main>

      <nav className='bg-white text-black w-full py-5 border-gray-200  border-0 border-t flex flex-column justify-around fixed bottom-0'>
          <BsFile className='text-gray-400 text-2xl' />
          <BsFiles className='text-gray-400 text-2xl' />
          <BsFileX className='text-gray-400 text-2xl' />
          {/*BsCheckCircle, BsCheckCircleFill, BsExclamationSquare, BsExclamationSquareFill,  BsDashCircle, BsDashCircleFill  */}
      </nav>
    </>
  )
}
